"""Tier B — BEV video with fragmented views (plan §3.2).

Same canonical 3D scene as Tier A, but rendered as a *sequence* of partial
BEV crops generated by a smoothed random-walk camera over the top-down plane.
Each frame shows only a window of the scene; the model must integrate across
frames to recover the full layout.

The camera is purely top-down orthographic, like Tier A — no perspective yet.
That is reserved for Tier C.
"""
from __future__ import annotations

import argparse
import random
from pathlib import Path
from typing import Any

from PIL import Image, ImageDraw

from ..scene import Camera, Frame, Scene
from ..utils import ensure_dir, load_yaml, set_seed
from .common import generate_3d_scene


def _world_to_image(
    xyz: tuple[float, float, float],
    x_range: tuple[float, float],
    y_range: tuple[float, float],
    image_size: int,
) -> tuple[float, float]:
    x, y, _ = xyz
    u = (x - x_range[0]) / (x_range[1] - x_range[0]) * image_size
    v = (1.0 - (y - y_range[0]) / (y_range[1] - y_range[0])) * image_size
    return u, v


def _radius_px(size_world: float, world_extent: float, image_size: int) -> float:
    return size_world / world_extent * image_size


def sample_trajectory(
    cfg: dict[str, Any], rng: random.Random
) -> list[tuple[float, float, float]]:
    """Sample a smoothed random-walk trajectory over the BEV plane.

    Returns a list of ``(cx, cy, half_window)`` triples — one per frame.
    """
    n = int(cfg["n_frames"])
    tcfg = cfg["trajectory"]
    half_w = float(tcfg["window_world_size"]) / 2.0
    step_sigma = float(tcfg["step_sigma"])
    momentum = float(tcfg["momentum"])
    zoom_sigma = float(tcfg.get("zoom_sigma", 0.0))
    clamp = tcfg.get("out_of_bounds", "clamp") == "clamp"
    x_lo, x_hi = cfg["working_volume"]["x"]
    y_lo, y_hi = cfg["working_volume"]["y"]

    if clamp:
        cx = rng.uniform(x_lo + half_w, x_hi - half_w)
        cy = rng.uniform(y_lo + half_w, y_hi - half_w)
    else:
        cx = rng.uniform(x_lo, x_hi)
        cy = rng.uniform(y_lo, y_hi)

    vx = rng.gauss(0.0, step_sigma)
    vy = rng.gauss(0.0, step_sigma)
    cur_half = half_w

    frames: list[tuple[float, float, float]] = []
    for _ in range(n):
        frames.append((cx, cy, cur_half))
        vx = momentum * vx + rng.gauss(0.0, step_sigma)
        vy = momentum * vy + rng.gauss(0.0, step_sigma)
        cx += vx
        cy += vy
        if clamp:
            cx = max(x_lo + cur_half, min(x_hi - cur_half, cx))
            cy = max(y_lo + cur_half, min(y_hi - cur_half, cy))
        if zoom_sigma > 0.0:
            cur_half = max(0.5, cur_half + rng.gauss(0.0, zoom_sigma))
    return frames


def _draw_frame(
    scene: Scene,
    cfg: dict[str, Any],
    cx: float,
    cy: float,
    half_w: float,
) -> tuple[Image.Image, Image.Image, list[list[float]], list[list[float]]]:
    image_size = int(cfg["image_size"])
    bg = int(cfg["background_gray"])
    x_range = (cx - half_w, cx + half_w)
    y_range = (cy - half_w, cy + half_w)
    world_extent = 2.0 * half_w

    img = Image.new("RGB", (image_size, image_size), (bg, bg, bg))
    mask = Image.new("L", (image_size, image_size), 0)
    draw_img = ImageDraw.Draw(img)
    draw_mask = ImageDraw.Draw(mask)

    for obj in scene.objects:
        u, v = _world_to_image(obj.centroid, x_range, y_range, image_size)
        r = _radius_px(cfg["sizes"][obj.size], world_extent, image_size)
        rgb = tuple(cfg["colors"][obj.color])
        bbox = (u - r, v - r, u + r, v + r)
        mid = obj.object_id + 1
        if obj.shape == "cube":
            draw_img.rectangle(bbox, fill=rgb)
            draw_mask.rectangle(bbox, fill=mid)
        elif obj.shape in ("sphere", "cylinder"):
            draw_img.ellipse(bbox, fill=rgb)
            draw_mask.ellipse(bbox, fill=mid)
        else:
            raise ValueError(f"unknown shape: {obj.shape}")

    fx = fy = image_size / world_extent
    cx_px = cy_px = image_size / 2.0
    K = [[fx, 0.0, cx_px], [0.0, fy, cy_px], [0.0, 0.0, 1.0]]
    # Camera at (cx, cy, 0) looking down -z; rotation = identity, translation = -(cx, cy, 0)
    E = [
        [1.0, 0.0, 0.0, -cx],
        [0.0, 1.0, 0.0, -cy],
        [0.0, 0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0, 1.0],
    ]
    return img, mask, K, E


def render_tier_b(
    scene: Scene,
    cfg: dict[str, Any],
    out_dir: Path,
    rng: random.Random,
) -> Scene:
    """Render a Tier B fragmented-BEV video for an existing 3D Scene.

    Returns a new Scene with ``tier="B"`` and ``n_frames`` Frame entries.
    The image, mask, and enriched ``scene.json`` are written to
    ``out_dir/<scene_id>/``. Frame ordering reflects rendering order; if
    ``temporal_shuffle`` is enabled, the frames list is permuted (frame_id
    values still encode the original chronological order so the analysis
    can recover both views).
    """
    trajectory = sample_trajectory(cfg, rng)
    scene_dir = ensure_dir(out_dir / scene.scene_id)
    ensure_dir(scene_dir / "frames")
    ensure_dir(scene_dir / "masks")

    new_frames: list[Frame] = []
    for i, (cx, cy, half_w) in enumerate(trajectory):
        img, mask, K, E = _draw_frame(scene, cfg, cx, cy, half_w)
        img_path = f"frames/{i:03d}.png"
        mask_path = f"masks/{i:03d}.png"
        img.save(scene_dir / img_path)
        mask.save(scene_dir / mask_path)
        new_frames.append(
            Frame(
                frame_id=i,
                image_path=img_path,
                mask_path=mask_path,
                camera=Camera(intrinsics=K, extrinsics=E, kind="orthographic"),
            )
        )

    if bool(cfg.get("temporal_shuffle", False)):
        rng.shuffle(new_frames)

    scene_out = Scene(
        scene_id=scene.scene_id,
        tier="B",
        objects=scene.objects,
        frames=new_frames,
        qa=list(scene.qa),
        extras={
            **scene.extras,
            "image_size": int(cfg["image_size"]),
            "n_frames": int(cfg["n_frames"]),
            "trajectory": [
                {"cx": float(cx), "cy": float(cy), "half": float(h)}
                for (cx, cy, h) in trajectory
            ],
            "temporal_shuffle": bool(cfg.get("temporal_shuffle", False)),
        },
    )
    scene_out.save(scene_dir)
    return scene_out


def render_scene(cfg: dict[str, Any], rng: random.Random, out_dir: Path) -> Scene:
    """Convenience: sample a 3D scene and immediately render its Tier B video."""
    scene = generate_3d_scene(cfg, rng, tier="3D")
    return render_tier_b(scene, cfg, out_dir, rng)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Render Tier B fragmented-BEV videos")
    p.add_argument("--config", type=str, required=True)
    p.add_argument("--out", type=str, required=True)
    p.add_argument(
        "--scenes-in",
        type=str,
        default=None,
        help="Directory of pre-generated 3D scenes; if set, --n-scenes is ignored",
    )
    p.add_argument("--n-scenes", type=int, default=None)
    p.add_argument("--n-frames", type=int, default=None,
                   help="Override n_frames from the config")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--limit", type=int, default=None,
                   help="Cap the number of scenes processed (for dev runs)")
    p.add_argument("--temporal-shuffle", action="store_true",
                   help="Permute the rendered frames (ablation from plan §3.2)")
    args = p.parse_args(argv)

    cfg = load_yaml(args.config)
    if args.n_frames is not None:
        cfg["n_frames"] = int(args.n_frames)
    if args.temporal_shuffle:
        cfg["temporal_shuffle"] = True
    out = ensure_dir(Path(args.out))
    set_seed(args.seed)

    try:
        from tqdm import tqdm
    except ImportError:
        def tqdm(x, **_):
            return x

    if args.scenes_in is not None:
        scenes_dir = Path(args.scenes_in)
        scene_dirs = sorted(
            d for d in scenes_dir.iterdir() if d.is_dir() and (d / "scene.json").exists()
        )
        if args.limit is not None:
            scene_dirs = scene_dirs[: args.limit]
        for d in tqdm(scene_dirs, desc="Tier B (render existing)"):
            scene = Scene.load(d)
            # Per-scene RNG so the trajectory is deterministic given (seed, scene_id)
            rng = random.Random(args.seed ^ (hash(scene.scene_id) & 0x7FFFFFFF))
            render_tier_b(scene, cfg, out, rng)
    else:
        n = int(args.n_scenes if args.n_scenes is not None else cfg.get("n_scenes", 5000))
        if args.limit is not None:
            n = min(n, args.limit)
        master_rng = random.Random(args.seed)
        for i in tqdm(range(n), desc="Tier B (sample + render)"):
            rng = random.Random(master_rng.randint(0, 2**31 - 1))
            render_scene(cfg, rng, out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
